### PR TITLE
Implementation of changes requested

### PR DESCRIPTION
**Pull request by AnXh3L0**

### CODE REVIEW

**Comment by AnXh3L0** [comment]
@greg0r this is mostly ready for review. The only items left to implement are the following:

- short description text in list: It would be good to have, if wanted by the author, the possibilty to
write a short preview text for the publication page instead of just showing the first two lines of the
whole description
- language: add the option to enter the language of the publication
- filter bug in the english language with a missing publication even when the filter is enabled

**Comment by AnXh3L0** [comment]
image

A preview of the current publication list

image

A preview of a publication

**Comment by AnXh3L0** [comment]
Short description text option has been added as well, now you can enter a custom/manual summary by adding a `summary` line in the front matter and filling it up the same way as all the other variables. 

The language for the posts has been added as well, now you can set the post language in the front matter as well, by using the `language` line.

**Comment by greg0r** [comment]
Thanks @AnXh3L0 , unfortunatlly there are some conflicts in the actual publication markups. Do you see them?

**Comment by AnXh3L0** [comment]
Hi @greg0r , yes, I see them, I will resolve those conflicts now.

**Comment by AnXh3L0** [comment]
Hi @greg0r, you can accept all incoming changes to those files in order to fix the conflicts as I don't have write access. Afterwards, the PR can be merged.

**Review by greg0r — APPROVED** [review]

**Comment by AnXh3L0** [comment]
@greg0r this is ready for merge!

**Pull request merged**
